### ISSUE TITLE
Ansible errors: master_discovery, docker-py and urlopen

### ISSUE THREAD

**Issue by koep** [dcos-labs/dcos-gce#7] opened 2016-09-30 11:23 UTC
I followed the instructions to deploy DC/OS to GCE and faced two issues:

`ansible-playbook -i hosts install.yml` yields the following error:

```
TASK [Generate customised build file] ******************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["/home/cko/dcos_generate_config.sh"], "delta": "0:00:00.824642", "end": "2016-09-30 08:37:09.038750", "failed": true, "rc": 1, "start": "2016-09-30 08:37:08.214108", "stderr": "\u001b[33m====> EXECUTING CONFIGURATION GENERATIONExecute the configuration generation (genconf).\u001b[0m\nGenerating configuration files...\n\u001b[1;31mmaster_discovery: Must set master_discovery, no way to calculate value.\u001b[0m", "stdout": "", "stdout_lines": [], "warnings": []}
```

I fixed this by adding master_discovery to the template/config.yaml file.

```
echo "master_discovery: static" >> template/config.yaml
```

After that, Ansible complained about docker-py:

```
TASK [start docker container] **************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error: docker-py version is 1.10.3. Minimum version required is 1.7.0."}
```

I had to downgrade docker-py manually. 

```
sudo pip install docker-py==1.7.0
```

Might be related to https://github.com/ansible/ansible/issues/17495

FYI I also get:

```
TASK [remove masters from known_hosts file] ************************************
failed: [localhost] (item=master0) => {"changed": true, "cmd": ["/usr/bin/ssh-keygen", "-R", "master0"], "delta": "0:00:00.008812", "end": "2016-09-30 11:15:02.139360", "failed": true, "item": "master0", "rc": 255, "start": "2016-09-30 11:15:02.130548", "stderr": "ssh-keygen: /root/.ssh/known_hosts: No such file or directory", "stdout": "", "stdout_lines": [], "warnings": []}
...ignoring

TASK [remove  masters IP from known_hosts file] ********************************
failed: [localhost] (item=master0) => {"changed": true, "cmd": ["/usr/bin/ssh-keygen", "-R", "10.132.0.3"], "delta": "0:00:00.004042", "end": "2016-09-30 11:15:02.463064", "failed": true, "item": "master0", "rc": 255, "start": "2016-09-30 11:15:02.459022", "stderr": "ssh-keygen: /root/.ssh/known_hosts: No such file or directory", "stdout": "", "stdout_lines": [], "warnings": []}
...ignoring
```

**Comment by koep** [comment] 2016-09-30 11:25
Some more info:

```
CentOS Linux release 7.2.1511 (Core) 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.2.1511 (Core) 
CentOS Linux release 7.2.1511 (Core)
```

```
sudo docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        
 OS/Arch:      linux/amd64
```

```
ansible 2.1.1.0
```

**Comment by ajazam** [comment] 2016-09-30 18:02
Thanks for the information. I'll have a look as soon as I can.

**Comment by ajazam** [comment] 2016-10-01 09:48
You need to make the following changes

in /usr/lib/system/system/docker.service make following change 
 "ExecStart=/usr/bin/dockerd --storage-driver=overlay" 

in groups_vars/all make following change

dcos_installer_download_path: "https://downloads.dcos.io/dcos/EarlyAccess/commit/4cfc235259a2375c558f2e1bab3564419110459e/dcos_generate_confi
g.sh?_ga=1.38184548.674486911.1475259096"

The above change will install dcos 1.8.2. Mesosphere are doing an official installation process which will be maintained by them https://mesosphere.com/blog/2016/09/29/making-dcos-run-great-on-google-cloud/  . The installation process will in the future be in sync with new releases of DCOS.

Let me know if this works for you.

**Comment by WonderPanda** [comment] 2016-10-04 01:31
@ajazam I was able to get a cluster up and running with the clarified instructions you've provided here. I also had to use `sudo pip install docker-py==1.7.0` as indicated above to get things running happily.

Now that I have this shiny cluster provisioned though I can't figure out how to access the web interface... Sorry for asking such a silly question but how do I access the cluster's dashboard now that it's up and running?

**Comment by ajazam** [comment] 2016-10-04 12:05
It's not a silly question. I had to resort to creating a windows server so I could use a browser. 

There must be a more elegant method of accessing the master and the agents!

**Comment by WonderPanda** [comment] 2016-10-04 12:58
I actually got things working last night. Just had to add a firewall rule to the default network that the agents live on to open up port 80 and then you can navigate to the external IP address of the master code and you're taken to the DC/OS dashboard. I'll add that information to the installation and PR it if you'd like.

**Comment by ajazam** [comment] 2016-10-06 19:49
The problem I have with your method is that's it's not secure. If there was an ssl certificate then I'd be happy to use it. https://dcos.io/docs/1.8/administration/securing-your-cluster/ I've just found this. I've not seen this before because I've been working on a different part of my technology stack.

**Comment by tobilg** [comment] 2016-10-07 07:52
@koep You seem to use Docker 1.12 which is not officially supported, see https://dcos.io/docs/1.8/administration/installing/custom/system-requirements/

> Version 1.12.x is not supported.

**Comment by swazza** [comment] 2016-10-07 08:20
To access the DC/OS dashboard, you can use ssh tunneling. I created an ssh key on my local machine

```
ssh-keygen -t rsa -f ~/.ssh/[KEYNAME] -C [USERNAME]
chmod 400 ~/.ssh/[KEYNAME]
pbcopy < ~/.ssh/[KEYNAME].pub
```

I added the SSH public key to the master0 VM instance's 'SSH Keys' section. Ran the following command from my local terminal after that - 

```
ssh -L 80:localhost:80 -f -N [USERNAME]@[master0 IP Address] -i [PATH TO PRIVATE KEY]
```

And then, navigate to localhost:80 on your browser and you should be able to access the DCOS dashboard.

Hope this helps. Thanks a lot for putting this repo together.

**Comment by ajazam** [comment] 2016-10-08 07:29
@swazza thanks. I'll have a look at that as soon as I can.

**Comment by ajazam** [comment] 2016-10-08 07:31
@tobilg I merged your PR, but I've just realised @koep has said that he to used docker-py v1.7

**Comment by tobilg** [comment] 2016-10-08 07:33
@ajazam As per https://github.com/ansible/ansible/issues/17495#issuecomment-246530778 the 1.9 version should work. Yesterday a user in the DC/OS Slack channel also verified this.

**Comment by ajazam** [comment] 2016-10-08 07:56
@tobilg I'll check that later this evening or tomorrow. I think I might also fix the docker version so the docker changes specified above do not have to be made.

**Comment by ajazam** [comment] 2016-10-11 23:07
I have just pushed in some changes. I can confirm that dcos 1.8.2 installs and works correctly. Can somebody please check? If nobody reports any problems then I will close this issue by the end of the week. The documentation on the main dcos website for this project hasn't been updated yet, but has been updated in this repository.

**Comment by ajazam** [comment] 2016-10-13 21:48
Th lastest changes have been tested with 1.7-open and 1.8.4. They appear to be working.

**Closed as completed by ajazam** 2016-10-13 21:48 UTC
